### ISSUE TITLE
Missing Licensing & copyright information

### ISSUE THREAD

**Issue by bperrybap** [adafruit/Adafruit_LiquidCrystal#7]
Library lacks a clear license and copyright notices.
Please add a licensing file that clearly indicates the licensing of the library.

The main header and .cpp files appear to be derivatives of the IDE LiquidCrystal library
The IDE LiquidCrystal  library is LGPL 2.1+ so this library must also adopt the LGPL 2.1+ license or it could be converted to GPL 3.0 if that is preferred as LGPL 2.1+ allows that.

The MCP23008 files in the utility directory can be licensed as BSD; however, if the library uses LGPL 2.1+ files, then the overall license for the library cannot be changed to BSD, MIT, or any other less restrictive license as the library uses LGPL 2.1+ files and LGPL does not allow conversion to a less restrictive license.

**Comment by caternuson** [comment]
Added with #16.

**Comment by bperrybap** [comment]
Ok, a license file was added but it is inconsistent with the origins of the code
and with a license statement in Adafruit_LiquidCrystal.cpp file which claims a BSD license.

My take is that the license for this library must be LGPL 2.1+ given it is a derivative of LGPL 2.1+ code.
